Compilation timestamp for struct.c: Wed Jun 16 18:47:31 2021
mocks.h:19: info: I - Automatically defined function: int enable_watchdog(int)
Compilation timestamp for struct.c: Tue Jun 29 19:11:48 2021
mocks.h:19: info: I - Automatically defined function: int enable_watchdog(int)
Compilation timestamp for struct.c: Tue Jun 29 19:16:43 2021
mocks.h:19: info: I - Automatically defined function: int enable_watchdog(int)
Compilation timestamp for struct.c: Thu Jul 01 16:24:32 2021
mocks.h:19: info: I - Automatically defined function: int enable_watchdog(int)
Compilation timestamp for struct.c: Wed Sep 08 21:23:38 2021
mocks.h:19: info: I - Automatically defined function: int enable_watchdog(int)
