dec:00@@disable_watchdog(int)
dec:00@@check_memory()
dec:00@@enable_watchdog(int)
dec:00@@_reclaim_reent(struct _reent*)
dec:00@@__locale_mb_cur_max()
dec:00@@abort()
dec:00@@abs(int)
dec:00@@arc4random()
dec:00@@arc4random_uniform(unsigned long)
dec:00@@arc4random_buf(void*, unsigned int)
dec:00@@atexit(void (*)())
dec:00@@atof(char const*)
dec:00@@atoff(char const*)
dec:00@@atoi(char const*)
dec:00@@_atoi_r(struct _reent*, char const*)
dec:00@@atol(char const*)
dec:00@@_atol_r(struct _reent*, char const*)
dec:00@@bsearch(void const*, void const*, unsigned int, unsigned int, int (*)(void const*, void const*))
dec:00@@div(int, int)
dec:00@@exit(int)
dec:00@@free(void*)
dec:00@@getenv(char const*)
dec:00@@_getenv_r(struct _reent*, char const*)
dec:00@@_findenv(char const*, int*)
dec:00@@_findenv_r(struct _reent*, char const*, int*)
dec:00@@getsubopt(char**, char* const*, char**)
dec:00@@labs(long)
dec:00@@ldiv(long, long)
dec:00@@mblen(char const*, unsigned int)
dec:00@@_mblen_r(struct _reent*, char const*, unsigned int, _mbstate_t*)
dec:00@@mbtowc(unsigned int*, char const*, unsigned int)
dec:00@@_mbtowc_r(struct _reent*, unsigned int*, char const*, unsigned int, _mbstate_t*)
dec:00@@wctomb(char*, unsigned int)
dec:00@@_wctomb_r(struct _reent*, char*, unsigned int, _mbstate_t*)
dec:00@@mbstowcs(unsigned int*, char const*, unsigned int)
dec:00@@_mbstowcs_r(struct _reent*, unsigned int*, char const*, unsigned int, _mbstate_t*)
dec:00@@wcstombs(char*, unsigned int const*, unsigned int)
dec:00@@_wcstombs_r(struct _reent*, char*, unsigned int const*, unsigned int, _mbstate_t*)
dec:00@@mkdtemp(char*)
dec:00@@mkstemp(char*)
dec:00@@mkstemps(char*, int)
dec:00@@mktemp(char*)
dec:00@@_mkdtemp_r(struct _reent*, char*)
dec:00@@_mkostemp_r(struct _reent*, char*, int)
dec:00@@_mkostemps_r(struct _reent*, char*, int, int)
dec:00@@_mkstemp_r(struct _reent*, char*)
dec:00@@_mkstemps_r(struct _reent*, char*, int)
dec:00@@_mktemp_r(struct _reent*, char*)
dec:00@@qsort(void*, unsigned int, unsigned int, int (*)(void const*, void const*))
dec:00@@rand()
dec:00@@realloc(void*, unsigned int)
dec:00@@reallocf(void*, unsigned int)
dec:00@@realpath(char const*, char*)
dec:00@@rpmatch(char const*)
dec:00@@srand(unsigned int)
dec:00@@strtod(char const*, char**)
dec:00@@_strtod_r(struct _reent*, char const*, char**)
dec:00@@strtof(char const*, char**)
dec:00@@strtol(char const*, char**, int)
dec:00@@_strtol_r(struct _reent*, char const*, char**, int)
dec:00@@strtoul(char const*, char**, int)
dec:00@@_strtoul_r(struct _reent*, char const*, char**, int)
dec:00@@system(char const*)
dec:00@@a64l(char const*)
dec:00@@l64a(long)
dec:00@@_l64a_r(struct _reent*, long)
dec:00@@on_exit(void (*)(int, void*), void*)
dec:00@@putenv(char*)
dec:00@@_putenv_r(struct _reent*, char*)
dec:00@@_reallocf_r(struct _reent*, void*, unsigned int)
dec:00@@setenv(char const*, char const*, int)
dec:00@@_setenv_r(struct _reent*, char const*, char const*, int)
dec:00@@__itoa(int, char*, int)
dec:00@@__utoa(unsigned int, char*, int)
dec:00@@itoa(int, char*, int)
dec:00@@utoa(unsigned int, char*, int)
dec:00@@rand_r(unsigned int*)
dec:00@@drand48()
dec:00@@_drand48_r(struct _reent*)
dec:00@@erand48(unsigned short*)
dec:00@@_erand48_r(struct _reent*, unsigned short*)
dec:00@@jrand48(unsigned short*)
dec:00@@_jrand48_r(struct _reent*, unsigned short*)
dec:00@@lcong48(unsigned short*)
dec:00@@_lcong48_r(struct _reent*, unsigned short*)
dec:00@@lrand48()
dec:00@@_lrand48_r(struct _reent*)
dec:00@@mrand48()
dec:00@@_mrand48_r(struct _reent*)
dec:00@@nrand48(unsigned short*)
dec:00@@_nrand48_r(struct _reent*, unsigned short*)
dec:00@@seed48(unsigned short*)
dec:00@@_seed48_r(struct _reent*, unsigned short*)
dec:00@@srand48(long)
dec:00@@_srand48_r(struct _reent*, long)
dec:00@@initstate(unsigned int, char*, unsigned int)
dec:00@@random()
dec:00@@setstate(char*)
dec:00@@srandom(unsigned int)
dec:00@@atoll(char const*)
dec:00@@_atoll_r(struct _reent*, char const*)
dec:00@@llabs(long long)
dec:00@@lldiv(long long, long long)
dec:00@@strtoll(char const*, char**, int)
dec:00@@_strtoll_r(struct _reent*, char const*, char**, int)
dec:00@@strtoull(char const*, char**, int)
dec:00@@_strtoull_r(struct _reent*, char const*, char**, int)
dec:00@@cfree(void*)
dec:00@@unsetenv(char const*)
dec:00@@_unsetenv_r(struct _reent*, char const*)
dec:00@@posix_memalign(void**, unsigned int, unsigned int)
dec:00@@_dtoa_r(struct _reent*, double, int, int, int*, int*, char**)
dec:00@@_malloc_r(struct _reent*, unsigned int)
dec:00@@_calloc_r(struct _reent*, unsigned int, unsigned int)
dec:00@@_free_r(struct _reent*, void*)
dec:00@@_realloc_r(struct _reent*, void*, unsigned int)
dec:00@@_mstats_r(struct _reent*, char*)
dec:00@@_system_r(struct _reent*, char const*)
dec:00@@__eprintf(char const*, char const*, unsigned int, char const*)
dec:00@@qsort_r(void*, unsigned int, unsigned int, void*, int (*)(void*, void const*, void const*))
dec:00@@_strtold_r(struct _reent*, char const*, char**)
dec:00@@strtold(char const*, char**)
dec:00@@aligned_alloc(unsigned int, unsigned int)
dec:00@@at_quick_exit(void (*)())
dec:00@@quick_exit(int)
def:00@@check_bus()
def:00@@mem_alloc(unsigned int)
def:00@@serial_com(s_TEST_COM*)
var:_impure_ptr
var:_global_impure_ptr
var:suboptarg
var:_testArray
cmd:c:\QADF60~1\cantata\bin\cppccd.exe!IPL!-F!IPL!../../ipg.cop!IPL!-F!IPL!test_struct/ipg.cop!IPL!--intdir:test_struct/!IPL!--comp:x86-win-gnuARM-LauterbachSim-c!IPL!--no_link!IPL!C:/GNUARM/54/bin/arm-none-eabi-gcc.exe!IPL!-c!IPL!-mthumb!IPL!-mcpu=ARM7TDMI!IPL!-mlittle-endian!IPL!-g!IPL!-o!IPL!test_struct/struct.o
dir:C:\Users\ph.stanek\workspace9\serial\Cantata\tests
fnm:../../struct.c
