def:00@@disable_watchdog(int)
dec:00@@check_memory()
dec:00@@enable_watchdog(int)
dec:00@@_reclaim_reent(struct _reent*)
dec:00@@__locale_mb_cur_max()
dec:00@@abort()
dec:00@@abs(int)
dec:00@@arc4random()
dec:00@@arc4random_uniform(unsigned long)
dec:00@@arc4random_buf(void*, unsigned int)
dec:00@@atexit(void (*)())
dec:00@@atof(char const*)
dec:00@@atoff(char const*)
dec:00@@atoi(char const*)
dec:00@@_atoi_r(struct _reent*, char const*)
dec:00@@atol(char const*)
dec:00@@_atol_r(struct _reent*, char const*)
dec:00@@bsearch(void const*, void const*, unsigned int, unsigned int, int (*)(void const*, void const*))
dec:00@@div(int, int)
dec:00@@exit(int)
dec:00@@free(void*)
dec:00@@getenv(char const*)
dec:00@@_getenv_r(struct _reent*, char const*)
dec:00@@_findenv(char const*, int*)
dec:00@@_findenv_r(struct _reent*, char const*, int*)
dec:00@@getsubopt(char**, char* const*, char**)
dec:00@@labs(long)
dec:00@@ldiv(long, long)
dec:00@@mblen(char const*, unsigned int)
dec:00@@_mblen_r(struct _reent*, char const*, unsigned int, _mbstate_t*)
dec:00@@mbtowc(unsigned int*, char const*, unsigned int)
dec:00@@_mbtowc_r(struct _reent*, unsigned int*, char const*, unsigned int, _mbstate_t*)
dec:00@@wctomb(char*, unsigned int)
dec:00@@_wctomb_r(struct _reent*, char*, unsigned int, _mbstate_t*)
dec:00@@mbstowcs(unsigned int*, char const*, unsigned int)
dec:00@@_mbstowcs_r(struct _reent*, unsigned int*, char const*, unsigned int, _mbstate_t*)
dec:00@@wcstombs(char*, unsigned int const*, unsigned int)
dec:00@@_wcstombs_r(struct _reent*, char*, unsigned int const*, unsigned int, _mbstate_t*)
dec:00@@mkdtemp(char*)
dec:00@@mkstemp(char*)
dec:00@@mkstemps(char*, int)
dec:00@@mktemp(char*)
dec:00@@_mkdtemp_r(struct _reent*, char*)
dec:00@@_mkostemp_r(struct _reent*, char*, int)
dec:00@@_mkostemps_r(struct _reent*, char*, int, int)
dec:00@@_mkstemp_r(struct _reent*, char*)
dec:00@@_mkstemps_r(struct _reent*, char*, int)
dec:00@@_mktemp_r(struct _reent*, char*)
dec:00@@qsort(void*, unsigned int, unsigned int, int (*)(void const*, void const*))
dec:00@@rand()
dec:00@@realloc(void*, unsigned int)
dec:00@@reallocf(void*, unsigned int)
dec:00@@realpath(char const*, char*)
dec:00@@rpmatch(char const*)
dec:00@@srand(unsigned int)
dec:00@@strtod(char const*, char**)
dec:00@@_strtod_r(struct _reent*, char const*, char**)
dec:00@@strtof(char const*, char**)
dec:00@@strtol(char const*, char**, int)
dec:00@@_strtol_r(struct _reent*, char const*, char**, int)
dec:00@@strtoul(char const*, char**, int)
dec:00@@_strtoul_r(struct _reent*, char const*, char**, int)
dec:00@@system(char const*)
dec:00@@a64l(char const*)
dec:00@@l64a(long)
dec:00@@_l64a_r(struct _reent*, long)
dec:00@@on_exit(void (*)(int, void*), void*)
dec:00@@putenv(char*)
dec:00@@_putenv_r(struct _reent*, char*)
dec:00@@_reallocf_r(struct _reent*, void*, unsigned int)
dec:00@@setenv(char const*, char const*, int)
dec:00@@_setenv_r(struct _reent*, char const*, char const*, int)
dec:00@@__itoa(int, char*, int)
dec:00@@__utoa(unsigned int, char*, int)
dec:00@@itoa(int, char*, int)
dec:00@@utoa(unsigned int, char*, int)
dec:00@@rand_r(unsigned int*)
dec:00@@drand48()
dec:00@@_drand48_r(struct _reent*)
dec:00@@erand48(unsigned short*)
dec:00@@_erand48_r(struct _reent*, unsigned short*)
dec:00@@jrand48(unsigned short*)
dec:00@@_jrand48_r(struct _reent*, unsigned short*)
dec:00@@lcong48(unsigned short*)
dec:00@@_lcong48_r(struct _reent*, unsigned short*)
dec:00@@lrand48()
dec:00@@_lrand48_r(struct _reent*)
dec:00@@mrand48()
dec:00@@_mrand48_r(struct _reent*)
dec:00@@nrand48(unsigned short*)
dec:00@@_nrand48_r(struct _reent*, unsigned short*)
dec:00@@seed48(unsigned short*)
dec:00@@_seed48_r(struct _reent*, unsigned short*)
dec:00@@srand48(long)
dec:00@@_srand48_r(struct _reent*, long)
dec:00@@initstate(unsigned int, char*, unsigned int)
dec:00@@random()
dec:00@@setstate(char*)
dec:00@@srandom(unsigned int)
dec:00@@atoll(char const*)
dec:00@@_atoll_r(struct _reent*, char const*)
dec:00@@llabs(long long)
dec:00@@lldiv(long long, long long)
dec:00@@strtoll(char const*, char**, int)
dec:00@@_strtoll_r(struct _reent*, char const*, char**, int)
dec:00@@strtoull(char const*, char**, int)
dec:00@@_strtoull_r(struct _reent*, char const*, char**, int)
dec:00@@cfree(void*)
dec:00@@unsetenv(char const*)
dec:00@@_unsetenv_r(struct _reent*, char const*)
dec:00@@posix_memalign(void**, unsigned int, unsigned int)
dec:00@@_dtoa_r(struct _reent*, double, int, int, int*, int*, char**)
dec:00@@_malloc_r(struct _reent*, unsigned int)
dec:00@@_calloc_r(struct _reent*, unsigned int, unsigned int)
dec:00@@_free_r(struct _reent*, void*)
dec:00@@_realloc_r(struct _reent*, void*, unsigned int)
dec:00@@_mstats_r(struct _reent*, char*)
dec:00@@_system_r(struct _reent*, char const*)
dec:00@@__eprintf(char const*, char const*, unsigned int, char const*)
dec:00@@qsort_r(void*, unsigned int, unsigned int, void*, int (*)(void*, void const*, void const*))
dec:00@@_strtold_r(struct _reent*, char const*, char**)
dec:00@@strtold(char const*, char**)
dec:00@@aligned_alloc(unsigned int, unsigned int)
dec:00@@at_quick_exit(void (*)())
dec:00@@quick_exit(int)
dec:00@@memchr(void const*, int, unsigned int)
dec:00@@strcoll(char const*, char const*)
dec:00@@strerror(int)
dec:00@@strtok(char*, char const*)
dec:00@@strxfrm(char*, char const*, unsigned int)
dec:00@@strtok_r(char*, char const*, char**)
dec:00@@bcmp(void const*, void const*, unsigned int)
dec:00@@bcopy(void const*, void*, unsigned int)
dec:00@@bzero(void*, unsigned int)
dec:00@@explicit_bzero(void*, unsigned int)
dec:00@@timingsafe_bcmp(void const*, void const*, unsigned int)
dec:00@@timingsafe_memcmp(void const*, void const*, unsigned int)
dec:00@@ffs(int)
dec:00@@index(char const*, int)
dec:00@@memccpy(void*, void const*, int, unsigned int)
dec:00@@rindex(char const*, int)
dec:00@@stpcpy(char*, char const*)
dec:00@@stpncpy(char*, char const*, unsigned int)
dec:00@@strcasecmp(char const*, char const*)
dec:00@@strdup(char const*)
dec:00@@_strdup_r(struct _reent*, char const*)
dec:00@@strndup(char const*, unsigned int)
dec:00@@_strndup_r(struct _reent*, char const*, unsigned int)
dec:00@@strerror_r(int, char*, unsigned int)
dec:00@@_strerror_r(struct _reent*, int, int, int*)
dec:00@@strlcat(char*, char const*, unsigned int)
dec:00@@strlcpy(char*, char const*, unsigned int)
dec:00@@strncasecmp(char const*, char const*, unsigned int)
dec:00@@strnlen(char const*, unsigned int)
dec:00@@strsep(char**, char const*)
dec:00@@strlwr(char*)
dec:00@@strupr(char*)
dec:00@@strsignal(int)
dec:00@@isalnum(int)
dec:00@@isalpha(int)
dec:00@@iscntrl(int)
dec:00@@isdigit(int)
dec:00@@isgraph(int)
dec:00@@islower(int)
dec:00@@isprint(int)
dec:00@@ispunct(int)
dec:00@@isspace(int)
dec:00@@isupper(int)
dec:00@@isxdigit(int)
dec:00@@tolower(int)
dec:00@@toupper(int)
dec:00@@isblank(int)
dec:00@@isascii(int)
dec:00@@toascii(int)
dec:00@@cppth_c_save_calls()
dec:00@@cppth_c_restore_calls()
dec:00@@cppth_memset(void*, int, unsigned int)
dec:00@@cppth_memcpy(void*, void const*, unsigned int)
dec:00@@cppth_start_script(char const*, int)
dec:00@@cppth_end_script(int)
dec:00@@cppth_start_test(char const*, char const*)
dec:00@@cppth_start_step(char const*)
dec:00@@cppth_start_step_not_run(char const*)
dec:00@@cppth_get_current_test_name()
dec:00@@cppth_record_coverage_by_test_case(int)
dec:00@@cppth_report_build_config()
dec:00@@cppth_end_test(int const, char const*)
dec:00@@cppth_end_step()
dec:00@@cppth_check_memory(char const*, void const*, void const*, unsigned int, int const, char const*)
def:00@@cppth_check_observation(char const*, char)
def:00@@cppth_check_observation_warn(char const*, char)
dec:00@@cppth_check_memory_warn(char const*, void const*, void const*, unsigned int, int const, char const*)
dec:00@@cppth_expected_calls(char const*)
dec:00@@cppth_expect_call(char const*, char const*, char const*)
dec:00@@cppth_default_expected_calls(char const*)
dec:00@@cppth_end_calls(int const, char const*)
dec:00@@cppth_reg_callinst(char const*)
dec:00@@cppth_reg_callfunc(char const*)
dec:00@@cppth_get_callinst()
dec:00@@cppth_valid_callinst(char const*)
dec:00@@cppth_get_loopindex(long)
dec:00@@cppth_call_seq_fail()
def:00@@cppth_start_timer()
def:00@@cppth_stop_timer()
def:00@@cppth_reset_timer()
def:00@@cppth_get_timer(, int)
dec:00@@cppth_open_log(int, char const*, int, int, char const*)
dec:00@@cppth_write_log(char const*, , int, int)
def:00@@cppth_write_log_user(char const*, , int)
dec:00@@cppth_close_log()
dec:00@@cppth_set_log_level()
dec:00@@cppth_get_log_level()
dec:00@@cppth_get_log_filename()
dec:00@@cppth_log_check_pass()
dec:00@@cppth_log_check_fail()
dec:00@@cppth_log_check_warn()
dec:00@@cppth_log_script_error(char const*)
dec:00@@cppth_lock_output(int)
dec:00@@cppth_output_line_and_file(int const, char const*, int const, char const*)
dec:00@@cppth_configure_enhanced_output(int const)
dec:00@@cppth_ostream_tag_on(int)
dec:00@@cppth_set_pending_posn(int const, char const*)
dec:00@@cppth_test_script_warning(char const*, int const, char const*)
dec:00@@cppth_initialise_pool(void*, unsigned int)
dec:00@@cppth_reportMemUsage()
dec:00@@cppth_strcmp(char const*, char const*)
def:00@@cppth_open_log_og(char const*, int, int)
dec:00@@cppth_check_address(char const*, void const*, void const*, int const, char const*)
dec:00@@cppth_check_address_warn(char const*, void const*, void const*, int const, char const*)
dec:00@@cppth_check_char(char const*, char, char, int const, char const*)
dec:00@@cppth_check_char_warn(char const*, char, char, int const, char const*)
dec:00@@cppth_check_double(char const*, long double, long double, int const, char const*)
dec:00@@cppth_check_double_warn(char const*, long double, long double, int const, char const*)
dec:00@@cppth_check_s_char(char const*, signed char, signed char, int const, char const*)
dec:00@@cppth_check_s_char_warn(char const*, signed char, signed char, int const, char const*)
dec:00@@cppth_check_s_int(char const*, long long, long long, int const, char const*)
dec:00@@cppth_check_s_int_warn(char const*, long long, long long, int const, char const*)
dec:00@@cppth_check_string(char const*, char const*, char const*, int const, char const*)
dec:00@@cppth_check_string_warn(char const*, char const*, char const*, int const, char const*)
dec:00@@cppth_check_u_char(char const*, unsigned char, unsigned char, int const, char const*)
dec:00@@cppth_check_u_char_warn(char const*, unsigned char, unsigned char, int const, char const*)
dec:00@@cppth_check_u_int(char const*, unsigned long long, unsigned long long, int const, char const*)
dec:00@@cppth_check_u_int_warn(char const*, unsigned long long, unsigned long long, int const, char const*)
dec:00@@cppth_check_boolean(char const*, int, int, int const, char const*)
dec:00@@cppth_check_boolean_warn(char const*, int, int, int const, char const*)
dec:00@@cppth_check_address_range(char const*, void const*, void const*, void const*, int const, char const*)
dec:00@@cppth_check_address_range_warn(char const*, void const*, void const*, void const*, int const, char const*)
dec:00@@cppth_check_char_range(char const*, char, char, char, int const, char const*)
dec:00@@cppth_check_char_range_warn(char const*, char, char, char, int const, char const*)
dec:00@@cppth_check_double_range(char const*, long double, long double, long double, int const, char const*)
dec:00@@cppth_check_double_range_warn(char const*, long double, long double, long double, int const, char const*)
dec:00@@cppth_check_s_char_range(char const*, signed char, signed char, signed char, int const, char const*)
dec:00@@cppth_check_s_char_range_warn(char const*, signed char, signed char, signed char, int const, char const*)
dec:00@@cppth_check_s_int_range(char const*, long long, long long, long long, int const, char const*)
dec:00@@cppth_check_s_int_range_warn(char const*, long long, long long, long long, int const, char const*)
dec:00@@cppth_check_string_range(char const*, char const*, char const*, char const*, int const, char const*)
dec:00@@cppth_check_string_range_warn(char const*, char const*, char const*, char const*, int const, char const*)
dec:00@@cppth_check_u_char_range(char const*, unsigned char, unsigned char, unsigned char, int const, char const*)
dec:00@@cppth_check_u_char_range_warn(char const*, unsigned char, unsigned char, unsigned char, int const, char const*)
dec:00@@cppth_check_u_int_range(char const*, unsigned long long, unsigned long long, unsigned long long, int const, char const*)
dec:00@@cppth_check_u_int_range_warn(char const*, unsigned long long, unsigned long long, unsigned long long, int const, char const*)
dec:00@@cppcg_resume_coverage()
dec:00@@cppcg_pause_coverage()
dec:00@@cppcg_reset_coverage()
dec:00@@cppcg_export_coverage(char const*, int)
dec:00@@cppcg_configure_coverage(char const*)
dec:00@@cppca_t2am03_programExit()
dec:00@@cppcr_import_coverage(char const*, int)
dec:00@@cppcr_report_coverage(int, char const*, int, char const*)
dec:00@@cppcr_trace_coverage(int, char const*, char const*)
dec:00@@cppcr_get_coverage_metric(int, char const*, int, char const*, int)
dec:00@@cppcr_get_coverage(int, char const*, int, char const*)
dec:00@@cppcr_get_coverage_min(int, char const*, int, char const*)
dec:00@@cppcr_get_coverage_max(int, char const*, int, char const*)
dec:00@@cppcr_get_coverage_avg(int, char const*, int, char const*)
dec:00@@cppcr_get_coverage_num(int, char const*, int, char const*)
dec:00@@cppcr_get_coverage_dev(int, char const*, int, char const*)
dec:00@@cppcr_get_coverage_wavg(int, char const*, int, char const*)
dec:00@@check_bus()
dec:00@@mem_alloc(unsigned int)
dec:00@@serial_com(s_TEST_COM*)
def:00@@disable_watchdog(int)
dec:00@@enable_watchdog(int)
def:00@@disable_watchdog(int)
def:00@@initialise_global_data()
def:00@@initialise_expected_global_data()
def:00@@check_global_data()
def:00@@run_tests()
def:00@@test_serial_com(int)
def:00@@test_serial_com_1(int)
def:00@@test_3(int)
def:00@@test_4(int)
def:00@@test_5(int)
def:00@@test_6(int)
def:00@@rule_set(char*, char*)
def:00@@main()
def:00@@run_tests()
def:00@@test_serial_com(int)
def:00@@test_serial_com_1(int)
def:00@@test_3(int)
def:00@@test_4(int)
def:00@@test_5(int)
def:00@@test_6(int)
def:00@@disable_watchdog(int)
var:_impure_ptr
var:_global_impure_ptr
var:suboptarg
var:__ctype_ptr__
var:_ctype_
var:cppth_enhanced_op_none
var:cppth_enhanced_op_stdout
var:cppth_enhanced_op_result
var:cppth_enhanced_op_fail
var:cppth_enhanced_op_pass
var:cppth_enhanced_op_warn
var:cppth_enhanced_op_covg
var:cppsm_replace_wrapper
var:cppsm_after_wrapper
var:cppth_default_file_size_limit
var:cppth_no_file_size_limit
var:cppca_none
var:cppca_export_replace
var:cppca_export_reset_after
var:cppca_import_replace
var:cppca_import_subtract
var:cppca_entrypoint_cov
var:cppca_callreturn_cov
var:cppca_statement_cov
var:cppca_basicblock_cov
var:cppca_decision_cov
var:cppca_booloper_cov
var:cppca_condition_cov
var:cppca_boolcomb_cov
var:cppca_multcond_cov
var:cppca_booleff_cov
var:cppca_maskeff_cov
var:cppca_relational_cov
var:cppca_loop_cov
var:cppca_include_infeasible
var:cppca_include_catch
var:cppca_by_function
var:cppca_exec_details
var:cppca_unexec_details
var:cppca_all_details
var:cppca_no_group_summary
var:cppca_no_overall_summary
var:cppca_coverage_metric
var:cppca_min_metric
var:cppca_max_metric
var:cppca_avg_metric
var:cppca_num_metric
var:cppca_dev_metric
var:cppca_wavg_metric
var:av_struct
var:expected_av_struct
var:cantata_memory_pool
cmd:c:\QADF60~1\cantata\bin\cppccd.exe!IPL!-F!IPL!../../ipg.cop!IPL!-F!IPL!test_struct/ipg.cop!IPL!--intdir:test_struct/!IPL!--comp:x86-win-gnuARM-LauterbachSim-c!IPL!--no_link!IPL!C:/GNUARM/54/bin/arm-none-eabi-gcc.exe!IPL!-c!IPL!-mthumb!IPL!-mcpu=ARM7TDMI!IPL!-mlittle-endian!IPL!-g!IPL!-o!IPL!test_struct/test_struct.o
dir:C:\Users\ph.stanek\workspace9\serial\Cantata\tests
fnm:test_struct/test_struct.c
